apiVersion: v1
kind: Service
metadata:
  name: {{ include "cc-fleet.fullname" . }}-session-manager
  labels:
    {{- include "cc-fleet.labels" . | nindent 4 }}
    {{- include "cc-fleet.sessionManager.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "cc-fleet.sessionManager.selectorLabels" . | nindent 4 }}
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
